//Em sequência estão: a variavel, o nome da variavel, uma lista com 2 objetos
let dados = [
    {   //Objeto sobre Alex Poatan
        titulo: "Alex Poatan Pereira: O Fenômeno do Kickboxing e MMA",
        descricao:"Alex Sandro Silva Pereira, mais conhecido como Alex Poatan, é um nome que ecoa com força nos mundos do kickboxing e do MMA. O brasileiro, natural de São Bernardo do Campo, construiu uma carreira meteórica, marcada por conquistas e feitos históricos. Antes de causar impacto no UFC, Poatan já era uma lenda no kickboxing. Com um estilo agressivo e nocautes devastadores, ele conquistou o cinturão dos pesos médios e meio-pesados do Glory, tornando-se o primeiro e único lutador a unificar os dois títulos na organização. A transição para o MMA foi rápida e bem-sucedida. Com apenas algumas lutas no UFC, Poatan desafiou e nocauteou Israel Adesanya, um dos maiores nomes da categoria, para se tornar campeão dos pesos médios. Em seguida, ele repetiu o feito na categoria meio-pesada, demonstrando um domínio impressionante e uma versatilidade técnica que poucos possuem. Com um estilo único ,Poatan é conhecido por sua força bruta, precisão nos golpes e capacidade de finalizar as lutas de forma espetacular. Seus nocautes viraram marca registrada, e sua postura confiante dentro do octógono o tornam um dos lutadores mais emocionantes de se assistir.",
        link: "https://pt.wikipedia.org/wiki/Alex_Pereira",
        tags: "Alex Pereira, Poatan, kickboxing, MMA, UFC, campeão, nocaute, lutas, artes marciais mistas, peso medio, médio, nocaute, cruzado de esquerda, cara de pedra, mão de pedra, mao, pedra, duplo caompeao, chama,",
        imagem: "imagens/img1.png",
        link2: "https://www.instagram.com/alexpoatanpereira/",
        link3:"https://youtu.be/ykTsOdbQjPo?si=UMfcy0E85zVHgDIa",
    },
    {      //Objeto sobre Charles do Bronx
        titulo: "Charles do Bronx: O Rei das Finalizações",
        descricao:" Charles Oliveira da Silva, mais conhecido como Charles do Bronx, é um dos lutadores brasileiros mais icônicos e bem-sucedidos da história do Ultimate Fighting Championship (UFC). Com um arsenal de finalizações impressionante e um coração de guerreiro, o carioca conquistou o coração dos fãs e se tornou um dos principais nomes do MMA mundial. zCharles detém o recorde de maior número de finalizações na história da organização. Sua especialidade são as submissões, principalmente as guilhotinas e os mata-leões, que já renderam diversas vitórias espetaculares. A trajetória de Charles no UFC foi marcada por altos e baixos. Ele já enfrentou dificuldades como cortes de peso e derrotas, mas sempre se mostrou resiliente e determinado a alcançar seus objetivos. Em 2021, o brasileiro realizou o sonho de conquistar o cinturão peso-leve do UFC, nocauteando Michael Chandler em uma luta emocionante. Em seu cartel consta nomes como Kevin Lee, Tony Ferguson, Michael Chandler, Dustin Poirier, Justin Gaethje, e Beneil Dariush",
        link: "https://pt.wikipedia.org/wiki/Charles_Oliveira",
        tags: " Charles do Bronx, Charles Oliveira, UFC, MMA, Jiu-Jitsu, finalização, campeão, peso-leve, brasileiro, peso leve, finalizacao, finalização,",
        imagem: "imagens/img2.png",
        link2: "https://www.instagram.com/charlesdobronxs/",
        link3:"https://youtu.be/9ckCtAZFM2g?si=t7yl2vLv2Nligl2r",

    },
    {      //Objeto sobre Conor Mc Gregor
        titulo: "Conor McGregor: O Notório Irlandês",
        descricao:" Conor McGregor é, sem dúvida, a figura mais carismática e controversa do mundo das artes marciais mistas (MMA). Com um estilo de luta agressivo e uma personalidade explosiva, o irlandês rapidamente se tornou um dos atletas mais populares e bem pagos do UFC. McGregor é conhecido por suas provocações, confiança inabalável e um estilo de vida extravagante. Essa personalidade forte o tornou uma figura icônica no esporte. Além do carisma, McGregor possui um talento indiscutível para o MMA. Sua combinação de striking preciso, movimentação rápida e inteligência tática o tornam um oponente formidável. O irlandês quebrou diversos recordes de pay-per-view e se tornou um dos maiores geradores de receita do UFC. McGregor se tornou o primeiro lutador na história do UFC a ser campeão em duas categorias de peso simultaneamente (peso pena e peso leve).",
        link: "https://pt.wikipedia.org/wiki/Conor_McGregor",
        tags: " Conor McGregor, MMA, UFC, campeão, peso pena, peso leve, Irlanda, luta, artes marciais mistas, irlanda, duplo caompeao,",
        imagem: "imagens/img3.png",
        link2: "https://www.instagram.com/thenotoriousmma/",
        link3:"https://youtu.be/3mPPMCa8Nxw?si=-F9DSaN6GgmfdpuK",
    },
    {      //Objeto sobre Anderson Silva 
        titulo: "Anderson Silva: A Lenda do MMA",
        descricao:" Anderson Silva, o lendário Spider, é amplamente reconhecido como um dos maiores lutadores de MMA de todos os tempos. Com um reinado dominante na categoria peso médio do UFC, onde defendeu o cinturão por 10 vezes consecutivas, e uma sequência invicta de 17 lutas, o brasileiro impressionou o mundo com seu estilo de luta elegante e preciso, marcado por nocautes espetaculares e uma calma ímpar. Através de uma técnica impecável e um carisma inigualável, o brasileiro dominou a categoria peso médio por anos, deixando um legado que dificilmente será igualado. Sua habilidade de antecipar os movimentos dos adversários e sua capacidade de finalizar lutas de forma espetacular o tornaram um ícone do esporte e um dos lutadores mais populares de todos os tempos.",
        link: "https://pt.wikipedia.org/wiki/Anderson_Silva",
        tags: "Anderson Silva, Spider, MMA, UFC, campeão, lenda, nocaute, artes marciais mistas, peso medio, médio, aranha, spider, lenda, goat, GOAT,",
        imagem: "imagens/img4.png",
        link2: "https://www.instagram.com/spiderandersonsilva/",
        link3:"https://youtu.be/6-XzIacyFT8?si=zzaJ4wBSUfN7QVod",
    },
    {      //Objeto sobre Jon Jones 
        titulo: "Jon Jones: O Dominador do Octógono",
        descricao:" Jon Jones é, sem dúvida, um dos maiores lutadores de MMA de todos os tempos. Conhecido por sua envergadura excepcional, técnica refinada e um histórico de vitórias quase impecável, 'Bones' ,como é carinhosamente apelidado,  deixou uma marca indelével no UFC. Durante anos, Jones reinou absoluto na divisão, defendendo o cinturão um número recorde de vezes e dominando adversários de forma esmagadora. Em 2023, Jon Jones deu um passo ousado e conquistou o cinturão dos pesos-pesados, demonstrando sua versatilidade e capacidade de se adaptar a diferentes estilos de luta. Jones é um mestre em diversas áreas do MMA, com destaque para o wrestling, jiu-jitsu e striking. Sua capacidade de combinar essas habilidades de forma fluida o torna um adversário extremamente difícil de ser vencido.",
        link: "https://pt.wikipedia.org/wiki/Jon_Jones",
        tags: "  Jon Jones, lenda, campeão, peso-meio-pesado, duplo caompeao, peso-pesado, meio pesado, peso pesado, goat, GOAT,",
        imagem: "imagens/img5.png",
        link2: "https://www.instagram.com/jonnybones/",
        link3:"https://youtu.be/8lKirrARb0w?si=gs9srs90nuhE5S7K",
    },
    {      //Objeto GSP 
        titulo: "Georges St-Pierre: A Lenda do Peso Meio-Médio",
        descricao:" Georges St-Pierre, frequentemente chamado de GSP, é outro nome que brilha intensamente no universo do MMA. Considerado por muitos como um dos maiores lutadores de todos os tempos, GSP deixou sua marca indelével no esporte, especialmente na divisão de peso meio-médio. Durante anos, GSP reinou supremo na divisão de peso meio-médio, defendendo o cinturão diversas vezes e dominando adversários com sua técnica impecável. GSP era conhecido por sua capacidade de adaptar seu estilo de luta de acordo com o adversário, sendo eficiente tanto na luta em pé quanto no chão. GSP sempre demonstrou um grande respeito por seus adversários e por esporte, sendo considerado um verdadeiro exemplo dentro e fora do octógono.",
        link: "https://pt.wikipedia.org/wiki/Georges_St._Pierre",
        tags: " Georges St-Pierre, GSP, campeão, peso meio-médio, peso medio,duplo caompeao, goat, GOAT,",
        imagem: "imagens/img6.png",
        link2: "https://www.instagram.com/georgesstpierre/",
        link3:"https://youtu.be/S5ZqBX9SMeQ?si=A_n71lf2Sj1n5FEH",
    },
    {      //Objeto sobre Jose Aldo
        titulo: "José Aldo: O Rei do Rio",
        descricao:" José Aldo, o Rei do Rio, é um dos maiores lutadores de MMA brasileiros de todos os tempos. Com um domínio absoluto na categoria peso pena, onde reinou por anos tanto no WEC quanto no UFC, Aldo se destacou por seus nocautes devastadores e técnica impecável. Treinado na renomada Chute Boxe, o brasileiro conquistou o coração dos fãs com seu estilo agressivo e preciso, consolidando seu status de lenda do esporte. Após uma trajetória repleta de conquistas, Aldo continua a competir no mais alto nível, inspirando novas gerações de lutadores.",
        link: "https://pt.wikipedia.org/wiki/Jos%C3%A9_Aldo",
        tags: "José Aldo, MMA, UFC, peso pena, campeão, nocaute, Chute Boxe, Brasil, peso pena, scar face, scarface,",
        imagem: "imagens/img7.png",
        link2: "https://www.instagram.com/josealdojunioroficial/",
        link3:"https://youtu.be/L8oht5ZNwFM?si=2df-gF5Kl6AY_vYc",
    },
    {      //Objeto sobre khabib 
        titulo: "Khabib Nurmagomedov: A Águia que Dominou o UFC",
        descricao:" Khabib Nurmagomedov é um nome que ecoa no mundo das artes marciais mistas (MMA) como sinônimo de domínio e invincibilidade. O lutador russo, de ascendência avare, construiu uma carreira impecável, marcada por uma sequência de vitórias que o consagrou como um dos maiores lutadores de todos os tempos. Khabib era conhecido por seu estilo de luta agressivo e dominante, baseado em um wrestling excepcional e um jogo de chão implacável. Sua capacidade de levar as lutas para o chão e finalizar seus oponentes com um ground and pound devastador era praticamente imbatível. Além disso, seu condicionamento físico era superior à maioria dos seus adversários, permitindo-lhe manter um ritmo intenso durante toda a luta.  Khabib conquistou o cinturão peso leve do UFC e o defendeu com sucesso em diversas oportunidades. Ao se aposentar, Khabib possuía um cartel impecável, com 29 vitórias e nenhuma derrota. Além de suas habilidades técnicas, Khabib era conhecido por sua mente forte e sua capacidade de intimidar seus adversários antes mesmo da luta começar.",
        link: "https://pt.wikipedia.org/wiki/Khabib_Nurmagomedov",
        tags: "Khabib Nurmagomedov, MMA, UFC, campeão, invicto, wrestling, Daguestão, Rússia, aguia,",
        imagem: "imagens/img8.png",
        link2: "https://www.instagram.com/khabib_nurmagomedov/",
        link3:"https://youtu.be/0rvIV_DGT1M?si=M8e8ql125HPvtzF-",
    },
    {      //Objeto sobre Adesanya 
        titulo: "Israel Adesanya: O Estilo e a Elegancia no Octógono",
        descricao:" Israel Adesanya é um dos nomes mais vibrantes e carismáticos do MMA moderno. Conhecido por seu estilo de luta elegante e imprevisível, o nigeriano conquistou o mundo das artes marciais mistas com sua habilidade técnica e sua presença magnética dentro do octógono. Adesanya possui uma base sólida em boxe, com uma combinação de golpes precisos e uma defesa impecável. Sua movimentação lateral e seus jabs rápidos são marcas registradas de seu estilo. Além do boxe, o nigeriano também é um especialista em chutes, com destaque para seus chutes circulares e chutes altos. Adesanya é conhecido por sua alta inteligência de luta, capaz de adaptar seu jogo de acordo com o adversário e encontrar brechas em suas defesas. Adesanya dominou a categoria peso médio por um período, defendendo o cinturão em diversas oportunidades. Em resumo, Israel Adesanya é mais do que apenas um lutador de MMA. Ele é um artista marcial completo, um showman e um ícone da cultura pop. Seu estilo de luta elegante, sua personalidade carismática e sua capacidade de entreter o público o tornam uma das figuras mais populares do esporte.",
        link: "https://pt.wikipedia.org/wiki/Israel_Adesanya",
        tags: " Israel Adesanya, MMA, UFC, campeão, estilo, elegante, boxe, chutes, carisma, personalidade, anime, avatar, style,",
        imagem: "imagens/img9.png",
        link2: "https://www.instagram.com/stylebender/",
        link3:"https://youtu.be/7kPYnUg8i-M?si=Za4QaO9rXg3PENXa",
    },
    {      //Objeto sobre Royce Gracie 
        titulo: "Royce Gracie: O Pai do MMA Moderno",
        descricao:" Royce Gracie é uma figura lendária no mundo das artes marciais mistas (MMA). Considerado por muitos como o pai do MMA moderno, ele revolucionou o esporte e popularizou o jiu-jitsu brasileiro em todo o mundo. Royce Gracie foi um dos principais competidores do primeiro Ultimate Fighting Championship (UFC), em 1993. Com uma técnica de jiu-jítsu impecável, ele derrotou adversários muito maiores e mais fortes, provando a eficácia da luta no chão e a importância do jiu-jítsu no MMA.  Antes de Royce Gracie, o jiu-jítsu brasileiro era pouco conhecido fora do Brasil. Com suas vitórias no UFC, ele popularizou a arte marcial e inspirou milhões de pessoas a praticá-la. O legado de Royce Gracie vai muito além de suas conquistas no octógono. Ele ajudou a moldar o MMA como conhecemos hoje e inspirou uma nova geração de lutadores.  O sucesso de Royce Gracie no UFC impulsionou o desenvolvimento do MMA, levando à criação de novas regras e organizações. O jiu-jítsu brasileiro se tornou uma das artes marciais mais populares do mundo, graças à exposição que recebeu através do MMA.",
        link: "https://pt.wikipedia.org/wiki/Royce_Gracie",
        tags: " Royce Gracie, MMA, jiu-jítsu, UFC, lenda, pioneiro, artes marciais mistas,",
        imagem: "imagens/img10.png",
        link2: "https://www.instagram.com/realroyce/",
        link3:"https://youtu.be/6GaSZoZaDbE?si=SXyp6pb7gc6qnDtI",
    },
    {      //Objeto sobre Dustin Poirier
        titulo: "Dustin Poirier: O Diamante do MMA",
        descricao:" Dustin Poirier é um dos lutadores mais respeitados e completos da atualidade no UFC. Conhecido por sua resiliência, coração de campeão e poder de nocaute, o americano conquistou o coração dos fãs com suas performances épicas no octógono.  Poirier teve uma infância humilde e começou a treinar artes marciais em tenra idade como uma forma de disciplina e autodefesa.  Sua jornada no MMA foi marcada por altos e baixos, mas sua determinação o levou a se tornar um dos principais atletas da categoria peso leve. Poirier é um lutador completo, com habilidades em pé e no chão. Sua trocação precisa e sua capacidade de finalizar lutas o tornam um oponente desafiador para qualquer adversário. Poirier já foi campeão interino dos pesos leves do UFC, demonstrando seu domínio na categoria.",
        link: "https://pt.wikipedia.org/wiki/Dustin_Poirier",
        tags: "Dustin Poirier, MMA, UFC, campeão, peso leve, luta, artes marciais mistas, diamante,",
        imagem: "imagens/img11.png",
        link2: "https://www.instagram.com/dustinpoirier/",
        link3:"https://youtu.be/cLcZTYIZQcI?si=wxFoI0pznTBQ0kdd",
    },
    {      //Objeto sobre stipe miocic
        titulo: "Stipe Miocic: O Maior Peso Pesado da História",
        descricao:" Stipe Miocic é um nome que ecoa com força no universo do MMA, especialmente na categoria peso pesado. O americano de origem croata é considerado um dos maiores lutadores da história da divisão, com um cartel impressionante e um reinado de sucesso no UFC.  Além de sua carreira no MMA, Miocic também é bombeiro, demonstrando uma incrível disciplina e dedicação.  Miocic é conhecido por sua combinação de wrestling, jiu-jitsu e striking, o que o torna um oponente perigoso em qualquer posição da luta. Seus golpes são devastadores, e ele já nocauteou alguns dos maiores nomes da categoria. Miocic foi campeão dos pesos pesados do UFC por diversas vezes, defendendo o cinturão contra adversários de alto nível.  Sua capacidade de aguentar o castigo e voltar a lutar é impressionante, o que o torna um verdadeiro guerreiro. Miocic se tornou um ícone do MMA, inspirando uma nova geração de lutadores.",
        link: "https://pt.wikipedia.org/wiki/Stipe_Mio%C4%8Di%C4%87",
        tags: " Stipe Miocic, MMA, UFC, campeão, peso pesado, luta, artes marciais mistas, goat, GOAT,",
        imagem: "imagens/img12.png",
        link2: "https://www.instagram.com/stipemiocic/",
        link3:"https://youtu.be/Jm4Qdx-RhJE?si=szv4Ye2-dcWXMvMx",
    },
    {      //Objeto sobre Glover Teixeira
        titulo: "Glover Teixeira: O Guerreiro Brasileiro do MMA",
        descricao:" Israel Adesanya é um dos nomes mais vibrantes e carismáticos do MMA moderno. Conhecido por seu estilo de luta elegante e imprevisível, o nigeriano conquistou o mundo das artes marciais mistas com sua habilidade técnica e sua presença magnética dentro do octógono. Adesanya possui uma base sólida em boxe, com uma combinação de golpes precisos e uma defesa impecável. Sua movimentação lateral e seus jabs rápidos são marcas registradas de seu estilo. Além do boxe, o nigeriano também é um especialista em chutes, com destaque para seus chutes circulares e chutes altos. Adesanya é conhecido por sua alta inteligência de luta, capaz de adaptar seu jogo de acordo com o adversário e encontrar brechas em suas defesas. Adesanya dominou a categoria peso médio por um período, defendendo o cinturão em diversas oportunidades. Em resumo, Israel Adesanya é mais do que apenas um lutador de MMA. Ele é um artista marcial completo, um showman e um ícone da cultura pop. Seu estilo de luta elegante, sua personalidade carismática e sua capacidade de entreter o público o tornam uma das figuras mais populares do esporte.",
        link: "https://pt.wikipedia.org/wiki/Glover_Teixeira",
        tags: "Glover Teixeira, MMA, UFC, campeão, meio-pesado, Brasil, luta, artes marciais mistas, coracao, heroi,",
        imagem: "imagens/img13.png",
        link2: "https://www.instagram.com/gloverteixeira/",
        link3:"https://youtu.be/0q82MwRoA80?si=G6bNGQfMzy5klAWk",
    },
];
